{% set name = "libsass" %}
{% set version = "0.14.4" %}
{% set sha256 = "14b1728537abf7640385e9382fb7b57d3f50eab48f813224bd321a25caed947f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win and py2k]

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - six

test:
  imports:
    - sass
    
about:
  home: https://github.com/dahlia/libsass-python
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'    
  # A pull request has been made to add LICENSE to manifest.in on libsass repo,
  # so after next release on pypi, we can use just "LICENSE" as the license_file
  # This is the link to that PR: https://github.com/dahlia/libsass-python/pull/216
  summary: 'A straightforward binding of libsass for Python. Compile Sass/SCSS in Python with no Ruby stack at all!'
  description: |
    This package provides a simple Python extension module sass which is binding 
    Libsass (written in C/C++ by Hampton Catlin and Aaron Leung). It's very 
    straightforward and there isn't any headache related Python distribution/deployment.
  doc_url: https://hongminhee.org/libsass-python/
  dev_url: https://github.com/dahlia/libsass-python

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - isuruf
