schema_version: 1

context:
  name: libsass
  version: 0.22.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sass/${{ name }}-python/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3ab5ad18e47db560f4f0c09e3d28cf3bb1a44711257488ac2adad69f4f7f8425
  patches:
    - 472.patch
    - 0001-Use-Constant.value-instead-of-Constant.s.patch

build:
  number: 3
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pysassc = pysassc:main

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - six
    - setuptools
  run:
    - python
    - six

tests:
  - python:
      imports:
        - sass
  - script:
      - pysassc --help

about:
  license: MIT
  license_file: LICENSE
  summary: A straightforward binding of libsass for Python. Compile Sass/SCSS in Python with no Ruby stack at all!
  description: |
    This package provides a simple Python extension module sass which is binding
    Libsass (written in C/C++ by Hampton Catlin and Aaron Leung). It's very
    straightforward and there isn't any headache related Python distribution/deployment.
  homepage: https://github.com/dahlia/libsass-python
  repository: https://github.com/dahlia/libsass-python
  documentation: https://hongminhee.org/libsass-python/

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - isuruf
    - marcelotrevisani
    - xhochy
