appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: sFv8rcOug9ZKuJQIj54n6MHOw7KZxOzlkfbaCe9EA0t10BVujh3t+BEL04ljUrhFHy3XefNZ5o9Z7ego48cGCDwQlESVB6n5IK/NuorQzHVaqFdyr/tpFRPVYlpV6WssVzhTuLS8ztQsY64Lpugtd9IgVY80UMr3//HOxXg2zhMiXPyunhcUhRXjvylqtyKgOdLhim7QnaXvqwClpqxbJUdubx6+RR/KhwxgQI1oqs529NiMAjWOzmsxwfhnsq3IWPXFqaSZqlNvYa3IWJ36aYkLauzGEPqjArVabxlQKWQozwpN68LBhSYHKlSb3LUAa6X62ffw8BdsgJCK0IyQWh98pQU3/PvLxYlWl2OS1WdYPE0zgR9B/WwBQv6wJo2k23IogWjE+0lH4SLQmju3J7lgTFf/1sNdgsXnk1KhqR4C+JvXke/lRhLfw2O3121kl42ItVWz1j9uNQTidu7bBn46Th9kh6lT8FGDH0ChvJYs3awF411D/b1FH4OOasnDx6UNcurwInMw45iNkIIhHFK69T2l5LyYWDzeLYkOkxwGRdECDPCpAv3FU8JsxiirZuihqkCYXhL9TrOzN+40eMjHAu6Xow0DzGUifgpWHcWWWTm72B4nUwkT8K5Ira2H2Hsjbwvye5dV//2vtSDRA2EdC+secqehQOWVme87GfU=}
provider:
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
